# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia o csproj correto e restaura pacotes
COPY ["API Central/API Central/APICentral.csproj", "API Central/API Central/"]
RUN dotnet restore "API Central/API Central/APICentral.csproj"

# Copia todo o restante e publica
COPY . .
WORKDIR "/src/API Central/API Central"
RUN dotnet publish -c Release -o /app/publish

# Etapa runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 5106
ENTRYPOINT ["dotnet", "APICentral.dll"]
